[[Dex]]
arch = "x86_64"
git-tree-sha1 = "028fbd90a895bb0eab2b9a68748f019b2d215572"
libc = "glibc"
os = "linux"

    [[Dex.download]]
    sha256 = "0c418094d1dec1c619d07ce3b5a2eebd9c6cb8078cd7b57493cd12394e26fc69"
    url = "https://github.com/JuliaBinaryWrappers/Dex_jll.jl/releases/download/Dex-v2.41.1+0/Dex.v2.41.1.x86_64-linux-gnu.tar.gz"
[[Dex]]
arch = "x86_64"
git-tree-sha1 = "e21a1ed1cdc45de82b4afdf7d9fb88ed98d4532f"
libc = "musl"
os = "linux"

    [[Dex.download]]
    sha256 = "dface55b0f8f7a88fb95f1e51d1ed3b1cf7a28a8819177063dc3e1440b42026a"
    url = "https://github.com/JuliaBinaryWrappers/Dex_jll.jl/releases/download/Dex-v2.41.1+0/Dex.v2.41.1.x86_64-linux-musl.tar.gz"
