[[Dex]]
arch = "x86_64"
git-tree-sha1 = "3f9fa2eb8376584566bbf0e1bae6db17deeab801"
libc = "glibc"
os = "linux"

    [[Dex.download]]
    sha256 = "25fe33973db236afd3a203a950e9126e7fa96c94ac542220146cc764bb351a59"
    url = "https://github.com/JuliaBinaryWrappers/Dex_jll.jl/releases/download/Dex-v2.30.2+2/Dex.v2.30.2.x86_64-linux-gnu.tar.gz"
[[Dex]]
arch = "x86_64"
git-tree-sha1 = "ac0a560c2de8ceb107cf9cacc5de0438f879d3fe"
libc = "musl"
os = "linux"

    [[Dex.download]]
    sha256 = "8f0e2acd36704c7c4e35342e5074167a897745cdeca3352234fcb2dac67af0b2"
    url = "https://github.com/JuliaBinaryWrappers/Dex_jll.jl/releases/download/Dex-v2.30.2+2/Dex.v2.30.2.x86_64-linux-musl.tar.gz"
