[[Dex]]
arch = "x86_64"
git-tree-sha1 = "1066834d5c7622b3e6b4ab40568421ec328712ec"
libc = "glibc"
os = "linux"

    [[Dex.download]]
    sha256 = "611f96f8a55e20ec0f8dc85a9d4e2e9e13a143740aeb54fb3f7ec1cd58996ed8"
    url = "https://github.com/JuliaBinaryWrappers/Dex_jll.jl/releases/download/Dex-v2.30.2+0/Dex.v2.30.2.x86_64-linux-gnu.tar.gz"
[[Dex]]
arch = "x86_64"
git-tree-sha1 = "9e64d32f1fee6bd058470ddaef5c20453ca0b666"
libc = "musl"
os = "linux"

    [[Dex.download]]
    sha256 = "1dd71351d3e3f6fc72796cfdbc34561f7a747b4ea52589f0bccfe67aa7da6a86"
    url = "https://github.com/JuliaBinaryWrappers/Dex_jll.jl/releases/download/Dex-v2.30.2+0/Dex.v2.30.2.x86_64-linux-musl.tar.gz"
